# Generated by Django 5.0 on 2023-12-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_pontosTuristicos',
            fields=[
                ('pon_id', models.AutoField(primary_key=True, serialize=False)),
                ('pon_nome', models.CharField(max_length=100)),
                ('pon_descricao', models.CharField(max_length=512)),
                ('pon_foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
