# Generated by Django 5.0 on 2024-01-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LIB', '0003_tb_pontosturisticos_pon_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_enderecoturistico',
            old_name='pon_latitude',
            new_name='end_latitude',
        ),
        migrations.RenameField(
            model_name='tb_enderecoturistico',
            old_name='pon_longitude',
            new_name='end_longitude',
        ),
        migrations.AlterField(
            model_name='tb_pontosturisticos',
            name='pon_qrcode',
            field=models.ImageField(blank=True, upload_to='imgs/'),
        ),
    ]
