# Generated by Django 5.0 on 2024-01-13 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LIB', '0004_rename_pon_latitude_tb_enderecoturistico_end_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_galeira_pontos_turisticos',
            fields=[
                ('gap_id', models.AutoField(primary_key=True, serialize=False)),
                ('gap_descricao', models.CharField(max_length=512)),
                ('gap_foto', models.ImageField(blank=True, upload_to='imgs/')),
            ],
        ),
        migrations.AddField(
            model_name='tb_favoritos',
            name='fav_pon_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_LIB.tb_pontosturisticos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tb_usuario_fisico',
            fields=[
                ('fis_id', models.AutoField(primary_key=True, serialize=False)),
                ('fis_foto', models.ImageField(blank=True, upload_to='imgs/')),
                ('fis_idade', models.IntegerField()),
                ('fis_sexo', models.CharField(max_length=15)),
                ('fis_nascimento', models.DateField()),
                ('fis_profissao', models.CharField(max_length=100)),
                ('fis_telefone', models.IntegerField()),
                ('fis_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tb_avaliacoes',
            fields=[
                ('ava_id', models.AutoField(primary_key=True, serialize=False)),
                ('ava_avaliacao', models.FloatField()),
                ('ava_comentario', models.CharField(max_length=512)),
                ('ava_nota', models.IntegerField()),
                ('ava_pon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_LIB.tb_pontosturisticos')),
                ('ava_fis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_LIB.tb_usuario_fisico')),
            ],
        ),
        migrations.AddField(
            model_name='tb_favoritos',
            name='fav_fis_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_LIB.tb_usuario_fisico'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tb_usuario_juridico',
            fields=[
                ('jur_id', models.AutoField(primary_key=True, serialize=False)),
                ('jur_nome_fantasia', models.CharField(max_length=100)),
                ('jur_telefone', models.IntegerField()),
                ('jur_foto', models.ImageField(blank=True, upload_to='imgs/')),
                ('jur_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
