# Generated by Django 5.0 on 2024-01-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LIB', '0006_alter_tb_galeira_pontos_turisticos_gap_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_galeira_pontos_turisticos',
            name='gap_pon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_LIB.tb_pontosturisticos'),
            preserve_default=False,
        ),
    ]
