# Generated by Django 5.0 on 2024-01-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_LIB', '0007_tb_galeira_pontos_turisticos_gap_pon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_usuario_fisico',
            name='fis_user',
        ),
    ]
