# Generated by Django 5.0 on 2024-01-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LIB', '0008_remove_tb_usuario_fisico_fis_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_galeria_avaliacao',
            fields=[
                ('gal_id', models.AutoField(primary_key=True, serialize=False)),
                ('gal_descricao', models.CharField(max_length=45)),
                ('gal_foto', models.ImageField(blank=True, upload_to='imgs_pon/')),
                ('gal_ava_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_LIB.tb_avaliacoes')),
            ],
        ),
    ]
